### NFC Data Test - Student
POST http://localhost:5000/attendance
Content-Type: application/json

{
  "nfc_data": "Student Details Name: Selvarasan Department: Al & DS Roll-no: 22AD093 Mobile:9361247573"
}

### NFC Data Test - Book
POST http://localhost:5000/nfc
Content-Type: application/json

{
  "nfc_data": "Book Details title: \"The Enchanted Forest\" author: \"Ava Green\" genre: \"Fantasy\""
}



### NFC Data Test - Book
POST http://localhost:5000/nfc
Content-Type: application/json

{
  "nfc_data": "Book Details title: \"Introduction to AI\" author: \"John Doe\" genre: \"Technology\""
}

### NFC Data Test - Unrecognized Data
POST http://localhost:5000/nfc
Content-Type: application/json

{
  "nfc_data": "Unknown Details title: \"Some title\" author: \"Unknown Author\" genre: \"Unknown Genre\""
}

### SIGNIN
POST http://localhost:5000/signin
Content-Type: application/json

{
    "username":"dp",
    "password":"0000"
}

### Session selector 
POST http://localhost:5000/library/select-action
Content-Type: application/json

{
  "action": "borrow"
  
}

### NFC Data Test - Book
POST http://localhost:5000/library
Content-Type: application/json

 {
  "nfc_data": "Student Details Name: Selvarasan Department: Al & DS Roll-no: 22AD093 Mobile:9361247573"
}

### NFC Data Test - Book
POST http://localhost:5000/library
Content-Type: application/json

{
  "nfc_data":"Book Details book_id:BK001 title:Introduction to AI  author: John Doe genre: Technology "

}

### Close the active session
POST http://localhost:5000/library/stop-session
Content-Type: application/json

### GET Students
GET http://localhost:5000/students

### GET Books
GET http://localhost:5000/books





